### ISSUE TITLE
Magento-Odoo Connector , Worker not showing - no workers 

### ISSUE THREAD

**Issue by diezcode** [OCA/connector-magento#134]
Hi,
I have installed the Magento Connector Modul. But in my Installation there are no workers. 
Why is that so?
http://odoo-magento-connector.com/guides/installation_guide.html

I can't make a worker and the process in the waitlist can be finished manually.

**Comment by lukebranch** [comment]
@diezcode ,

I'm only another user like yourself, however I've run into that issue before.

I'd recommend referring here to see if it resolves your issue:

https://bugs.launchpad.net/openerp-connector/+bug/1281073

are you running a multi-database instance by any chance?

**Comment by diezcode** [comment]
@lukebranch 
yes I have 6 database in that odoo instance

**Comment by guewen** [comment]
@diezcode you do not anymore need workers, please use the new job runner: http://odoo-connector.com/guides/jobrunner.html

**Comment by diezcode** [comment]
Can you please show me in wich Files this must be included?

How to use it?
Set the following environment variables:
ODOO_CONNECTOR_CHANNELS=root:4 (or any other channels configuration)
optional if xmlrpc_port is not set: ODOO_CONNECTOR_PORT=8069
Start Odoo with –load=web,connector and –workers > 1. [2]
Disable then “Enqueue Jobs” cron.
Do NOT start openerp-connector-worker.
Create jobs (eg using base_import_async) and observe they start immediately and in parallel.

What Files and how to start odoo : like this? sudo service odoo start -load=web,connector and -workers > 1

Or how?

**Comment by IJOL** [comment]
Hi, all:

I had ( yesterday ) this very same problem, that it turn out to be a problem with the PostgreSQL server itself, it seems thr watcher therad  was stuck trying to initialize one of the db, so finally the watcher thread was not inited, we suspect that only restarting pg the problem could have gone, but before that we simply deleted the rogue db, and at the next restart the problem was gone..

Hope that helps, it took some hours and debugging to get to know the culprit was pg... no odoo
