### ISSUE TITLE
odoo_magento_connector installation

### ISSUE THREAD

**Issue by gemchand** [OCA/connector-magento#139]
hello ;

can every one to help me how to connect magento ecommerce  to odoo ?
can you  give complete procedure how to install this and integrate it to the magento ?
thank you

**Comment by pedrobaeza** [comment]
Check http://odoo-magento-connector.com/

**Comment by rivelta** [comment]
@pedrobaeza : stupid answer !! everone has benn follow but doc its not clear

**Comment by pedrobaeza** [comment]
No, it's the question which is stupid: http://www.catb.org/esr/faqs/smart-questions.html

**Comment by rivelta** [comment]
lolz see people problem fat old man :
- https://www.odoo.com/forum/help-1/question/problem-installing-magento-connector-84559

- https://stackoverflow.com/questions/40450437/odoo-magento-2-connection-issue

- https://github.com/OCA/connector-magento/issues/166

the main stupid doc is :
1. not tell how to config http auth both magento and odoo
2. not tell where is file config and how to config for accessing magento or odoo db
3. the doc only tell how to install regulary not detail ( shit like your answer )
4. the server_enviroment_files not included ( blank folder test )

if u can doit just tell how to , not only says link ( really stupid answer )

**Comment by guewen** [comment]
> not tell how to config http auth both magento and odoo

http://odoo-magento-connector.com/guides/installation_guide.html#configuring-the-magento-web-services



> not tell where is file config and how to config for accessing magento or odoo db

There is no particular configuration file needed for this connector, besides the regular odoo and magento configuration files.



> the doc only tell how to install regulary not detail ( shit like your answer )

Contributions welcome on https://github.com/OCA/connector-magento/



> the server_enviroment_files not included ( blank folder test )

Server environment files is not a requirement for this module and is only an extension of the base 'server_environment' module. There is no server_environment_files shipped because this is not how it works, you would have such an addon in every addon-path and it would serve nothing. https://github.com/OCA/server-tools/tree/10.0/server_environment

Now, @rivelta if you say that doc is not clear, you are free to ask precise questions and contribute back to improve the documentation, but you are clearly not welcome to come here and speak about stupid and shit about this work that represents hundreds of hours of work and is nevertheless distributed freely (as in free speech and in free beers) and even less insulting people. I hope you'll understand and consider again how you want to speak to contributors.
