### ISSUE TITLE
[8.0] Product Taxes not mapped on import

### ISSUE THREAD

**Issue by thomich** [OCA/connector-magento#150]
If products are imported (directly or with sale order import), no tax of imported magento product is mapped with the odoo product tax and still it just uses the default tax configured in odoo.

In magento, we have products with different taxes, eg. 8%, 2.5% and so on. After import products, in odoo all products get the default tax of 8% which is completely wrong.

Why isn't that implemented in magentoerpconnect?
Is it implemented in any other module, which is still not merged, migrated into 8.0?

Thanks for reply...

Regards
thomi

**Comment by guewen** [comment]
Yes, the default taxes of the products are applied. The taxes need to be configured both on Odoo and Magento. The Magento API does not give information about the tax that it applies so we can't make the link. (In fact the only info we can have is the percentage, which is something we can't rely on since we can have several taxes with the same).
