### ISSUE TITLE
I want to connect odoo 12 to magento 2.3.4 

### ISSUE THREAD

**Issue by walidromdhani** [OCA/connector-magento#300]
I am a beginner and I need advice [End of studies project] 

I want to connect audio 12 to Magento 2.3.4 using the old magenta connector. 
It's possible!!
 it's possible with old-Magento-connector?
And  I have found in the documentation some points that impose questions for me for example:
 1) Compatible with the latest version of Odoo 8.0 and the latest versions of Magento. 
2) I can't find this path "  In the Magento admin panel, go to System > Web-Services > SOAP/XML-RPC - Roles. " 

Please, if you have any idea guide me

**Comment by StefanRijnhart** [comment]
As I mentioned on the other ticket, I will finish the port of Magento2 compatibility for the module on Odoo 12 in a couple of weeks, and I'd love it if you could do some testing then.

**Comment by StefanRijnhart** [comment]
If you want, you can have a look at https://github.com/VanMoof/connector-magento/tree/add/12.0/magento2. It might still be a bit rough but I'd appreciate the feedback.

**Comment by PhilippeBach** [comment]
> If you want, you can have a look at https://github.com/VanMoof/connector-magento/tree/add/12.0/magento2. It might still be a bit rough but I'd appreciate the feedback.

mostiy it work   pretty god  just hava a problem with url encoding when you have "/" slash in products sku   the profided sku is not encoded  it result and error 404 

odoo.addons.queue_job.exception.FailedJobError: Max. retries (5) reached: A network error caused the failure of the job: 404 Client Error: Not Found for url: https://*******/index.php/rest/V1/products/SC6/8SPG
the sku is SC6/8SPG   should be  slash encoded 

the other issue is to add pub to url  because in standard magento 2.3 installation  medias are located in pub folder 
for entry in data.get('media_gallery_entries', []):
            if entry['media_type'] == 'image':
                entry['url'] = '%s/pub/media/catalog/product/%s' % (
                    self.backend_record.location, entry['file'])
                res.append(entry)
        return res

**Comment by StefanRijnhart** [comment]
Thanks @PhilippeBach! As discussed in our private email conversation, I fixed these issues in my 12.0 branch for which there is now a PR: https://github.com/OCA/connector-magento/pull/304.
